[package]
name = "snops"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["ws"] }
bimap.workspace = true
bincode.workspace = true
chrono = { workspace = true, features = ["serde"] }
clap.workspace = true
duration-str = { version = "0.7", default-features = false }
external-ip.workspace = true
fixedbitset = "0.5.6"
futures-util.workspace = true
hmac = "0.12.1"
http.workspace = true
indexmap.workspace = true
jwt = "0.16.0"
lazy_static.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rayon.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = ["stream", "json"] }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde_with = "3.7"
sha2 = "0.10.8"
snops-common = { path = "../snops-common" }
strum_macros = "0.26"
surrealdb = { version = "1.3", default-features = false, features = [
	"kv-rocksdb",
] }
tarpc.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing-appender.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "fast-rng"] }
wildmatch = "2.3.3"
