[workspace]
members = [
	"crates/aot",
	"crates/snot",
	"crates/snot-agent",
	"crates/snot-cli",
	"crates/snot-common",
]
resolver = "2"

[workspace.dependencies]
aleo-std = "=0.1.24"
anyhow = "1"
bimap = "0.6"
bincode = "1.3"
clap = { version = "4.5", features = ["derive"] }
colored = "2"
futures = "0.3"
futures-util = "0.3.30"
http = "1.1"
indexmap = { version = "2.2", features = ["serde"] }
indicatif = { version = "0.17", features = ["rayon"] }
lazy_static = "1.4"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1"
regex = "1.10"
reqwest = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tarpc = { version = "0.34", features = ["tokio1", "serde1"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full", "macros"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nix = { version = "0.28", features = ["process"] }

snarkos-account = { path = "../snarkos/account" }
snarkos-cli = { path = "../snarkos/cli" }
snarkos-node = { path = "../snarkos/node" }
snarkvm = { path = "../snarkvm", features = ["rocks"] }
snot-common = { path = "./crates/snot-common" }

[patch."https://github.com/AleoHQ/snarkVM.git"]
snarkvm = { path = "../snarkvm" }
