[workspace]
members = [
	"crates/aot",
	"crates/snops",
	"crates/snops-agent",
	"crates/snops-cli",
	"crates/snops-common",
]
resolver = "2"

[profile.dev]
codegen-units = 512
opt-level = 1

# This one optimizes performance
[profile.release]
codegen-units = 1
incremental = true
lto = "fat"
opt-level = 3
panic = "abort"
strip = true

# For testing cargo bloat
[profile.release-no-strip]
inherits = "release"
strip = false

# This one optimizes binary size
[profile.release-small]
inherits = "release"
opt-level = "z"

[workspace.dependencies]
aleo-std = "=0.1.24"
axum = "0.7"
anyhow = "1"
bimap = "0.6"
bincode = "1.3"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
clap_complete = { version = "4.5" }
colored = "2"
external-ip = "4.2"
futures = "0.3"
futures-util = "0.3"
http = "1.1"
indexmap = { version = "2.2", features = ["serde"] }
indicatif = { version = "0.17", features = ["rayon"] }
lazy_static = "1.4"
lasso = { version = "0.7", features = ["multi-threaded"] }
rand = "0.8"
rand_chacha = "0.3"
rayon = "1"
regex = "1.10"
reqwest = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tarpc = { version = "0.34", features = ["tokio1", "serde1"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full", "macros"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"
uuid = "1.8"
nix = { version = "0.28", features = ["process"] }

snarkos-account = { path = "../snarkos/account" }
snarkos-cli = { path = "../snarkos/cli" }
snarkos-node = { path = "../snarkos/node" }
snarkvm = { path = "../snarkvm", features = ["rocks"] }
snops-common = { path = "./crates/snops-common" }
crossterm = "0.27"
duration-str = { version = "0.7", default-features = false }
fixedbitset = "0.5"
hmac = "0.12"
httpdate = "1.0"
jwt = "0.16"
local-ip-address = "0.6"
metrics-exporter-prometheus = "0.13"
rocksdb = { version = "0.21", default-features = false }
serde-clap-deserialize = "0.1"
serde_with = "3.7"
sha2 = "0.10"
simple_moving_average = "1.0"
strum_macros = "0.26"
surrealdb = { version = "1.3", default-features = false }
tokio-tungstenite = "0.21"
tracing-flame = "0.2"
wildmatch = "2.3"

[patch."https://github.com/AleoHQ/snarkVM.git"]
snarkvm = { path = "../snarkvm" }
