[workspace]
members = ["crates/aot", "crates/infra"]
resolver = "2"

[workspace.dependencies]
aleo-std = "=0.1.24"
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
colored = "2"
indexmap = { version = "2.2", features = ["serde"] }
indicatif = { version = "0.17", features = ["rayon"] }
rand = "0.8"
rand_chacha = "0.3"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"

[workspace.dependencies.snarkos-cli]
path = "../snarkos/cli"

[workspace.dependencies.snarkvm]
path = "../snarkvm"
