[package]
name = "snot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = "0.7.4"
axum-typed-websockets = { version = "0.6.0", default-features = false }
bincode = { workspace = true }
duration-str = { version = "0.7", default-features = false }
indexmap = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
snarkos-aot = { path = "../aot" }
snot-common = { path = "../snot-common", features = ["server"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
