global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets: [localhost:9090]
  - job_name: snops
    honor_timestamps: true
    honor_labels: true
    http_sd_configs:
      - url: http://host.docker.internal:1234/prometheus/httpsd
        refresh_interval: 15s
