[package]
name = "snot-common"
version = "0.1.0"
edition = "2021"

[features]
client = []
server = []

[dependencies]
lazy_static = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
