[package]
name = "snot-common"
version = "0.1.0"
edition = "2021"

[features]
client = []
server = []

[dependencies]
futures.workspace = true
lazy_static.workspace = true
regex.workspace = true
serde.workspace = true
tarpc.workspace = true
tokio.workspace = true
