name: PR
on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # TODO move to a release ci
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         path: snarkos-test

  #     - name: Checkout snarkOS
  #       uses: actions/checkout@v4
  #       with:
  #         repository: AleoNet/snarkOS
  #         path: snarkos

  #     - name: Checkout snarkVM
  #       uses: actions/checkout@v4
  #       with:
  #         repository: AleoNet/snarkVM
  #         path: snarkvm

  #     - name: Use mold linker
  #       uses: rui314/setup-mold@v1

  #     - name: Install nightly and cranelift
  #       uses: dtolnay/rust-toolchain@nightly
  #       with:
  #         toolchain: nightly-2024-04-01
  #         components: rustc-codegen-cranelift-preview

  #     - uses: Swatinem/rust-cache@v2
  #       with:
  #         workspaces: snarkos-test
  #         key: cache-v1

  #     - name: Build
  #       working-directory: ./snarkos-test
  #       env:
  #         RUSTFLAGS: -Zcodegen-backend=cranelift -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
  #       run: cargo +nightly-2024-04-01 build --verbose

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          path: snarkos-test

      - name: 📥 Checkout snarkOS
        uses: actions/checkout@v4
        with:
          repository: AleoHQ/snarkOS
          fetch-depth: 0
          ref: 9be1039d7426040e15299631d59a66a8d97251a7 # latest canarynet
          path: snarkos

      - name: 📥 Checkout snarkVM
        uses: actions/checkout@v4
        with:
          repository: AleoHQ/snarkVM
          fetch-depth: 0
          ref: aef07da8ed38aa4c3cdb2d946e0b6c783cc72cd3 # latest canarynet
          path: snarkvm

      - name: ☁️ Install Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: 📋 Format Check
        working-directory: ./snarkos-test
        run: cargo +nightly fmt -- --check

  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          path: snarkos-test

      - name: 📥 Checkout snarkOS
        uses: actions/checkout@v4
        with:
          repository: AleoHQ/snarkOS
          fetch-depth: 0
          ref: dde9e176123130355a4686cf8241f111e04094b3 # latest canarynet
          path: snarkos

      - name: 📥 Checkout snarkVM
        uses: actions/checkout@v4
        with:
          repository: AleoHQ/snarkVM
          fetch-depth: 0
          ref: da3d78a5726ce5b07581203a9aaff3fe39fc3057 # latest canarynet
          path: snarkvm

      - name: 🥬 Use Mold Linker
        uses: rui314/setup-mold@v1

      - name: ☁️ Install Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-04-01
          components: rustc-codegen-cranelift-preview clippy

      - name: 🫙 Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: snarkos-test
          key: cache-v1
          cache-on-failure: true

      - name: ☁️ Install Nextest
        uses: taiki-e/install-action@nextest

      # - name: ☁️ Install cargo-machete
      # run: cargo install cargo-machete

      # - name: 📋 Clippy Check
      #   working-directory: ./snarkos-test
      #   env:
      #     RUSTFLAGS: -Zcodegen-backend=cranelift
      #   run: cargo +nightly-2024-04-01 clippy --all --all-targets -- -D warnings

      # - name: 📋 Check Unused Deps
      #   if: always()
      #   working-directory: ./snarkos-test
      #   env:
      #     RUSTFLAGS: -Zcodegen-backend=cranelift
      #   run: cargo machete

      - name: 🧪 Test
        if: always()
        working-directory: ./snarkos-test
        env:
          RUSTFLAGS: -Zcodegen-backend=cranelift
        run: cargo +nightly-2024-04-01 nextest run --all --verbose --fail-fast
