name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: snarkos-test

      - name: Checkout snarkOS
        uses: actions/checkout@v4
        with:
          repository: AleoNet/snarkOS
          path: snarkos

      - name: Checkout snarkVM
        uses: actions/checkout@v4
        with:
          repository: AleoNet/snarkVM
          path: snarkvm

      - name: Use mold linker
        uses: rui314/setup-mold@v1

      - name: Install nightly and cranelift
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustc-codegen-cranelift-preview

      - uses: Swatinem/rust-cache@v2
        with:
          key: cache-v1

      - name: Build
        working-directory: ./snarkos-test
        env:
          RUSTFLAGS: -Zcodegen-backend=cranelift
        run: cargo +nightly build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: snarkos-test

      - name: Checkout snarkOS
        uses: actions/checkout@v4
        with:
          repository: AleoNet/snarkOS
          path: snarkos

      - name: Checkout snarkVM
        uses: actions/checkout@v4
        with:
          repository: AleoNet/snarkVM
          path: snarkvm

      - name: Use mold linker
        uses: rui314/setup-mold@v1

      - name: Install nightly and cranelift
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustc-codegen-cranelift-preview

      - uses: Swatinem/rust-cache@v2
        with:
          key: cache-v1

      - uses: taiki-e/install-action@nextest

      - name: Run tests
        working-directory: ./snarkos-test
        env:
          RUSTFLAGS: -Zcodegen-backend=cranelift
        run: cargo +nightly nextest --all --verbose
